# Generated by Django 5.1.2 on 2024-10-21 17:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'current_balance',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20
                    ),
                ),
                (
                    'freeze_balance',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20
                    ),
                ),
                (
                    'asset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='chain.asset'
                    ),
                ),
                (
                    'key_pair',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='chain.encryptedkeypair',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('user', 'asset'), name='unique_user_asset_wallet'
                    )
                ],
            },
        ),
    ]
