# Generated by Django 5.1.2 on 2024-10-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='family',
            field=models.CharField(
                choices=[('EVM', 'EVM'), ('BTC', 'Bitcoin'), ('SOL', 'Solana')],
                default='EVM',
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name='network',
            constraint=models.UniqueConstraint(
                fields=('name', 'family'), name='unique_network_and_family'
            ),
        ),
    ]
